### ISSUE TITLE
Function parametrize produces incorrect urls

### ISSUE THREAD

**Issue by ioncreature** [cre-o/ok.ru#3] opened 2015-07-07 16:26 UTC
``` js
ok.get({
    method: 'photos.getPhotos',
    param1: undefined,
    param2: undefined
}, callback );
```

Produces urls like
`method=photos.getPhotos&param1=undefined&param2=undefined`

instead of 
`method=photos.getPhotos&param1=&param2=`

**Comment by cre-o** [comment] 2019-02-18 19:32
Closing this issue because anybody is confirmed need of this feature.

**Closed by cre-o** 2019-02-18 19:32 UTC
